export const profileHobbyOptions = [
  // Музика та мистецтво
  { value: "music", label: "Музыка" },
  { value: "music_instruments", label: "Игра на инструментах" },
  { value: "singing", label: "Пение" },
  { value: "concerts", label: "Концерты" },
  { value: "art", label: "Искусство" },
  { value: "drawing", label: "Рисование" },
  { value: "painting", label: "Живопись" },
  { value: "handmade", label: "Рукоделие" },
  { value: "theatre", label: "Театр" },
  { value: "cinema", label: "Кинематограф" },
  { value: "movies", label: "Кино" },
  { value: "photo", label: "Фотография" },
  { value: "photography_nature", label: "Фото природы" },
  { value: "street_photo", label: "Уличная фотография" },
  { value: "video_editing", label: "Монтаж видео" },
  { value: "design", label: "Дизайн" },
  { value: "architecture", label: "Архитектура" },
  // Рух та спорт
  { value: "sport", label: "Спорт" },
  { value: "fitness", label: "Фитнес" },
  { value: "yoga", label: "Йога" },
  { value: "running", label: "Бег" },
  { value: "cycling", label: "Велосипед" },
  { value: "swimming", label: "Плавание" },
  { value: "football", label: "Футбол" },
  { value: "basketball", label: "Баскетбол" },
  { value: "tennis", label: "Теннис" },
  { value: "skiing", label: "Лыжи" },
  { value: "surfing", label: "Серфинг" },
  { value: "hiking", label: "Походы" },
  { value: "camping", label: "Кемпинг" },
  { value: "fishing", label: "Рыбалка" },
  { value: "dance", label: "Танцы" },
  { value: "martial_arts", label: "Боевые искусства" },
  { value: "boxing", label: "Бокс" },
  { value: "gym", label: "Тренажёрный зал" },
  { value: "climbing", label: "Скалолазание" },
  { value: "horse_riding", label: "Верховая езда" },
  // Подорожі та природа
  { value: "travel", label: "Путешествия" },
  { value: "nature", label: "Природа" },
  { value: "gardening", label: "Садоводство" },
  { value: "flowers", label: "Цветы" },
  { value: "pets", label: "Животные" },
  { value: "astronomy", label: "Астрономия" },
  // Книги, навчання, творчість
  { value: "books", label: "Книги" },
  { value: "reading", label: "Чтение" },
  { value: "poetry", label: "Поэзия" },
  { value: "writing", label: "Писательство" },
  { value: "history", label: "История" },
  { value: "science", label: "Наука" },
  { value: "psychology", label: "Психология" },
  { value: "languages", label: "Языки" },
  { value: "learning", label: "Обучение" },
  { value: "teaching", label: "Преподавание" },
  { value: "self_development", label: "Саморазвитие" },
  { value: "meditation", label: "Медитация" },
  { value: "spirituality", label: "Духовность" },
  // Їжа та кулінарія
  { value: "cooking", label: "Кулинария" },
  { value: "healthy_food", label: "Здоровое питание" },
  { value: "vegan", label: "Веганство" },
  { value: "wine", label: "Вино" },
  { value: "coffee", label: "Кофе" },
  { value: "craft_beer", label: "Крафтовое пиво" },
  // Технології та геймінг
  { value: "tech", label: "Технологии" },
  { value: "gaming", label: "Игры" },
  { value: "board_games", label: "Настольные игры" },
  { value: "chess", label: "Шахматы" },
  { value: "puzzles", label: "Пазлы" },
  { value: "esports", label: "Киберспорт" },
  { value: "streaming", label: "Стриминг" },
  { value: "podcasts", label: "Подкасты" },
  { value: "blogging", label: "Блогинг" },
  { value: "vlogging", label: "Видеоблоги" },
  { value: "drones", label: "Дроны" },
  { value: "diy", label: "Сделай сам" },
  // Стиль та авто
  { value: "fashion", label: "Мода" },
  { value: "cars", label: "Авто" },
  { value: "motorcycle", label: "Мото" },
  { value: "tattoos", label: "Тату" },
  // Фінанси та бізнес
  { value: "startups", label: "Стартапы" },
  { value: "investing", label: "Инвестиции" },
  { value: "crypto", label: "Криптовалюты" },
  // Інше
  { value: "volunteer", label: "Волонтерство" },
  { value: "collecting", label: "Коллекционирование" },
  { value: "modeling", label: "Моделирование" },
  { value: "anime", label: "Аниме" },
  { value: "comics", label: "Комиксы" },
  { value: "social", label: "Общение" },
  { value: "party", label: "Вечеринки" },
  { value: "quiet_evenings", label: "Тихие вечера" },
  { value: "kids", label: "Дети" },
  { value: "family", label: "Семья" },
];

/** Повернути label за value (для відображення збережених хобі) */
export function getHobbyLabel(value) {
  return profileHobbyOptions.find((i) => i.value === value)?.label ?? value;
}
